'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Footer from './components/footer'
import { ReduxProvider } from '@/redux/provider'
import Navbar from "./components/navigation/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <div className="main-container">
            <ReduxProvider>
               <Navbar />

               {children}
            </ReduxProvider>
            <Footer />
          </div>
        </body>
      </html>
  )
}
